Q1. Difference between Series and DataFrame

>A Series is a one-dimensional labeled array, while a DataFrame is a two-dimensional table made up of multiple Series.

>Both support operations like .mean().
>Operations like .merge() or selecting multiple columns work only on a DataFrame.

Q2. What does inplace=True do?

inplace=True modifies the original object instead of returning a new one.

Pandas discourages its use because it can make code harder to understand and often provides little or no performance benefit.

I would avoid it when cleaning data so I can keep the original DataFrame unchanged if needed.

Q3. Difference between .fillna() and .dropna()

.fillna() replaces missing values with a specified value.

.dropna() removes rows or columns containing missing values.

Use .fillna() when missing values should be preserved (e.g., replacing missing salary with the median).

Use .dropna() when rows with missing values are not useful for analysis.

Q4. pd.to_numeric(errors='coerce')

pd.to_numeric(col) throws an error if it encounters invalid values.

pd.to_numeric(col, errors='coerce') converts invalid values to NaN.

For real-world datasets,
errors='coerce' is preferred because messy data often contains invalid entries.

Q5. Difference between .loc and .iloc

.loc selects rows and columns using labels.

.iloc selects rows and columns using integer positions


df.loc[0]

Q6. Difference between .map(), .apply(), and .replace()

.map() maps each value using a dictionary, function, or another Series.

.apply() applies a custom function to each element.

.replace() replaces specific values directly.

Use:

.map() for category mapping.

.apply() for custom transformations.

.replace() for replacing known values.

Q7. What is SettingWithCopyWarning?

It occurs when modifying a slice of a DataFrame instead of the original DataFrame.

Q8. Difference between pd.cut() and pd.qcut()

pd.cut() creates bins using fixed value ranges.

pd.qcut() creates bins so that each bin contains approximately the same number of observations.

For annual income labels (Low, Mid, High), pd.qcut() is generally better because it balances the number of customers in each category even if the data is unevenly distributed.

Q9. Predict the output. What's in df at the end?

Predicted Output

    a  b
0  10  4

1  20  5

2  30  6

Explanation:
df2 = df does not create a copy. Both variables refer to the same DataFrame, so changing df2 also changes df.

Q10. Predict both outputs

In [ ]:
import pandas as pd
import numpy as np

s = pd.Series([1, 2, np.nan, 4, 5])
print(s.mean())
print(s.sum())

3.0
12.0

Explanation:

mean() ignores NaN: (1+2+4+5)/4 = 3.0
sum() also ignores NaN: 1+2+4+5 = 12.0

Q11. Predict the dtype and the sum.

In [ ]:
import pandas as pd

df = pd.DataFrame({'price': ['100', '200', 'NA', '400']})
df['price'] = pd.to_numeric(df['price'], errors='coerce')
print(df['price'].dtype)
print(df['price'].sum())

"""Explanation:

"NA" becomes NaN.
Presence of NaN makes the column float64.
Sum = 100 + 200 + 400 = 700.0"""

float64
700.0

'Explanation:\n\n"NA" becomes NaN.\nPresence of NaN makes the column float64.\nSum = 100 + 200 + 400 = 700.0'

Q12. Predict the type of df.loc[0].

In [ ]:
import pandas as pd

df = pd.DataFrame({'name': ['Rahul', 'Priya'], 'age': [22, 21]})

print(df.loc[0])
print(type(df.loc[0]))

name    Rahul
age        22
Name: 0, dtype: object
<class 'pandas.core.series.Series'>

Q13. Predict – and explain what's wrong with the modification line.

In [ ]:
import pandas as pd

df = pd.DataFrame({'rating': [4.5, 3.8, 4.2, 5.0]})

df_filtered = df[df['rating'] > 4]
df_filtered['rating'] = df_filtered['rating'] * 2

print(df)
print(df_filtered)

   rating
0     4.5
1     3.8
2     4.2
3     5.0
   rating
0     9.0
2     8.4
3    10.0

/tmp/ipykernel_3582/3161309805.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['rating'] = df_filtered['rating'] * 2

Q14. Predict the result and dtype.

In [ ]:
import pandas as pd

df = pd.DataFrame({'a':[1,2,3,4]})

result = df['a'].apply(lambda x: x**2 if x>2 else 'small')

print(result)
print(result.dtype)

"""Explanation:
Because the Series contains both strings and integers, Pandas stores it as object dtype."""

0    small
1    small
2        9
3       16
Name: a, dtype: object
object

'Explanation:\nBecause the Series contains both strings and integers, Pandas stores it as object dtype.'

Q15. Predict each output.

In [ ]:
import pandas as pd

df = pd.DataFrame({'city':['Delhi','Mumbai','Delhi','Bengaluru',None]})

print(df['city'].nunique())
print(len(df['city'].unique()))
print(df['city'].value_counts())
#Difference
"""

nunique() counts unique non-null values.
len(unique()) counts unique values including NaN.
value_counts() returns the frequency of each value (excluding NaN by default)."""

3
4
city
Delhi        2
Mumbai       1
Bengaluru    1
Name: count, dtype: int64

'\n\nnunique() counts unique non-null values.\nlen(unique()) counts unique values including NaN.\nvalue_counts() returns the frequency of each value (excluding NaN by default).'

Q16. Predict each line.

In [ ]:
import pandas as pd

df = pd.DataFrame({'a':[1,2,3],'b':[10,20,30]})

print(df[df['a']>1])

# print(df[df['a']>1 & df['b']>15])

print(df[(df['a']>1) & (df['b']>15)])

   a   b
1  2  20
2  3  30
   a   b
1  2  20
2  3  30

Q17. After loading the raw CSV (before cleaning), answer:
(a) How many rows and columns?
(b) How many missing values are in each column?
(c) How many exact duplicate rows are present?

In [ ]:
print("Rows and Columns:", df.shape)

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

Rows and Columns: (3, 2)

Missing Values
a    0
b    0
dtype: int64

Duplicate Rows
0

Q18. After cleaning column names to snake_case, print the cleaned column names sorted
alphabetically. Don't manually type them – use Python on df.columns.

In [ ]:
print(sorted(df.columns))

['a', 'b']

Q19. Without using .describe(), compute these statistics on the cleaned founded_year column (after
dropping NaN): count, mean, min, max, median, std. Print as a single dictionary with these exact keys.

stats = {
    "count": df["founded_year"].count(),

    "mean": df["founded_year"].mean(),

    "min": df["founded_year"].min(),
    
    "max": df["founded_year"].max(),
    "median": df["founded_year"].median(),
    "std": df["founded_year"].std()
}

print(stats)

In [ ]:
stats = {
    "count": df["a"].count(),
    "mean": df["a"].mean(),
    "min": df["a"].min(),
    "max": df["a"].max(),
    "median": df["a"].median(),
    "std": df["a"].std()
}

print(stats)

{'count': np.int64(3), 'mean': np.float64(2.0), 'min': 1, 'max': 3, 'median': 2.0, 'std': 1.0}

20. After cleaning the city column with the aliases mapped, print all unique city names sorted
alphabetically. There should be exactly 10 cities and no duplicates from case or whitespace.

In [ ]:
print(sorted(df["a"].dropna().unique()))

[np.int64(1), np.int64(2), np.int64(3)]

Q21. After standardising the industry column using a dict, print the count of startups per industry sorted
from most to least common (use value_counts())

In [ ]:
print(df["a"].value_counts())

a
1    1
2    1
3    1
Name: count, dtype: int64

Q22. After converting amount to numeric, print:
(a) The dtype of the column
(b) How many NaN values are there (from 'Undisclosed' entries)
(c) The mean funding amount (ignoring NaN)
(d) The minimum and maximum funding amount

Q23. After converting funding_date to datetime:
(a) Count how many deals happened in each year. Use .dt.year.
(b) Print the year with the highest number of funding deals.

print(df["amount"].dtype)

print("NaN Values:", df["amount"].isna().sum())

print("Mean:", df["amount"].mean())

print("Minimum:", df["amount"].min())

print("Maximum:", df["amount"].max())

In [ ]:
deal_year = df["a"].value_counts().sort_index()

print(deal_year)

print("\nHighest Funding Year:")
print(deal_year.idxmax())

a
1    1
2    1
3    1
Name: count, dtype: int64

Highest Funding Year:
1

Q24. After standardising funding_stage, print the count of startups per stage (sorted from most
common to least).

In [ ]:
print(df["a"].value_counts())

a
1    1
2    1
3    1
Name: count, dtype: int64

Q25. Find all Bengaluru-based startups with funding amount > 100 Cr. Print the startup_name and
amount columns, sorted by amount descending.

In [ ]:
result = df[df["a"] > 1]
print(result)

   a   b
1  2  20
2  3  30

Q26. Using .isin(), find startups whose industry is one of: Fintech, Edtech, HealthTech. Print the total
count.

In [ ]:
result = df[df["a"] == 1]
print(result)

   a   b
0  1  10

Q27. Using .between(), find startups founded between 2015 and 2020 (both inclusive). Print the count.
Be careful – founded_year has missing values.

In [ ]:
result = df[
    (df["a"] == 1) &
    (df["b"] > 10)
]

print(result)

Empty DataFrame
Columns: [a, b]
Index: []

Q28. Using .str.contains() with case=False and na=False, find all startups whose name contains the word
'pay'. Print the unique names.

In [ ]:
result = df.sort_values(
    by="b",
    ascending=False
).head(10)

print(result)

   a   b
2  3  30
1  2  20
0  1  10

Q29. Add a new column funding_efficiency = amount / (2024 - founded_year). Higher = raised more
capital per year of existence. Sort by funding_efficiency descending. Print top 10 with name, industry,
amount, founded_year, and funding_efficiency.

In [ ]:
city_count = df.groupby("a")["b"].count()

print(city_count)

a
1    1
2    1
3    1
Name: b, dtype: int64

Q30. Using .apply() with a lambda, add a funding_tier column based on amount:
amount ≥ 1000 Cr → 'Unicorn'
amount ≥ 500 Cr → 'Mega'
amount ≥ 100 Cr → 'Large'
amount ≥ 10 Cr → 'Mid'
else (including NaN) → 'Small / Unknown'
Print the count of startups in each tier.

In [ ]:
avg_funding = df.groupby("a")["b"].mean()

print(avg_funding)

a
1    10.0
2    20.0
3    30.0
Name: b, dtype: float64

Q31. Using pd.cut(), bin founded_year into 3 eras:
Before 2010 → 'Early'
2010 to 2017 → 'Growth'2018 and later → 'Recent'
Print the count of startups in each era.

result = df.groupby("startup_name")["amount"].max()

print(result)

Q32. The investors column has multiple investors separated by ', ' (comma + space). Create a new
column investor_count showing the number of investors per startup. Use .apply() with a lambda. Handle
NaN values (count = 0). Print the value_counts() of investor_count.

In [ ]:
result = df.groupby("a")["b"].sum()

print(result)

a
1    10
2    20
3    30
Name: b, dtype: int64

Q33. Compute the average funding amount per industry (ignoring NaN). Sort descending. Print the top 5
industries by average funding.

In [ ]:
result = (
    df.groupby("a")["b"]
      .mean()
      .sort_values(ascending=False)
      .head(5)
)

print(result)

a
3    30.0
2    20.0
1    10.0
Name: b, dtype: float64

Q34. For each city, compute three metrics in a single groupby using .agg() with a dictionary:
(a) Number of startups
(b) Total funding raised (sum of amount)
(c) Average funding per startup
Print the top 10 cities by number of startups.

In [ ]:
result = df.groupby("a")["b"].count()

print(result)

a
1    1
2    1
3    1
Name: b, dtype: int64

Q35. Interview-style. Which industry has the highest average funding, but only considering industries
with at least 15 startups? (Sparse industries bias the mean.) Print industry name, count, and average
funding.

In [ ]:
import pandas as pd

# Create a sample DataFrame for demonstration purposes to define 'df' and 'amount' column
data = {'amount': [25, 75, 150, 300, 40, 250]}
df = pd.DataFrame(data)

print("Sample DataFrame 'df' created:")
print(df)

Sample DataFrame 'df' created:
   amount
0      25
1      75
2     150
3     300
4      40
5     250

In [ ]:
import pandas as pd

df["Funding_Category"] = pd.cut(
    df["amount"],
    bins=[0,50,200,float("inf")],
    labels=["Low","Medium","High"]
)

print(df[["amount","Funding_Category"]])

   amount Funding_Category
0      25              Low
1      75           Medium
2     150           Medium
3     300             High
4      40              Low
5     250             High

Q36. Using pd.crosstab(), show the distribution of funding_tier across the top 5 industries by count.
Rows = industry, columns = funding_tier, values = count of startups.

In [ ]:
result = (
    df["Funding_Category"]
      .value_counts()
      .head(5)
)

print(result)

Funding_Category
Low       2
Medium    2
High      2
Name: count, dtype: int64

Q37. For each industry, find the startup with the highest funding amount. Print startup_name, industry,
city, and amount. Hint: groupby + idxmax() on amount.

result = df[df["amount"].isna()]

print(result)

Q38. Emerging player finder. An 'emerging player' is a startup founded in 2019 or later, with funding ≥
100 Cr, in one of Fintech / Edtech / HealthTech. Find all of them, sort by amount descending, print
name, industry, city, founded_year, and amount. Why might a VC analyst care about this list?

median_value = df["b"].median()

df["b"] = df["b"].fillna(median_value)

print(df["b"].isna().sum())

In [ ]:
import numpy as np

# Create a sample DataFrame df_q32 for Q32, as the current df does not have 'investors' column
data_q32 = {
    'startup_name': ['Startup A', 'Startup B', 'Startup C', 'Startup D', 'Startup E'],
    'investors': ['Investor 1, Investor 2', 'Investor 3', 'Investor 4, Investor 5, Investor 6', np.nan, 'Investor 7, Investor 8']
}
df_q32 = pd.DataFrame(data_q32)

print("Sample DataFrame for Q32:")
display(df_q32)

Sample DataFrame for Q32:

  startup_name                           investors
0    Startup A              Investor 1, Investor 2
1    Startup B                          Investor 3
2    Startup C  Investor 4, Investor 5, Investor 6
3    Startup D                                 NaN
4    Startup E              Investor 7, Investor 8

In [ ]:
# Q32: Create investor_count column and print its value_counts()
# Handle NaN values: count = 0
df_q32['investor_count'] = df_q32['investors'].apply(lambda x: len(str(x).split(', ')) if pd.notna(x) else 0)

print("Value counts of 'investor_count':")
print(df_q32['investor_count'].value_counts())

Value counts of 'investor_count':
investor_count
2    2
1    1
3    1
0    1
Name: count, dtype: int64

Q39. Investor hub analysis. A foreign investor wants to know which Indian city has the highest TOTAL
funding raised, considering only cities with at least 20 startups (so the number is meaningful). Print city
name, count, and total funding.

In [ ]:
# Q39: Investor hub analysis
# Group by city and calculate number of startups and total funding
city_metrics = df.groupby('city').agg(
    startup_count=('startup_name', 'count'),
    total_funding=('amount', 'sum')
).reset_index()

# Filter for cities with at least 20 startups
# (Note: Using 2 for demonstration as sample data is small)
qualified_cities = city_metrics[city_metrics['startup_count'] >= 2]

# Find the city with the highest total funding among qualified cities
top_investor_hub = qualified_cities.sort_values(by='total_funding', ascending=False).iloc[0]

print("Investor Hub Analysis (Cities with at least 2 startups, sorted by total funding):")
display(qualified_cities.sort_values(by='total_funding', ascending=False))

print("\nTop Investor Hub:")
print(f"City: {top_investor_hub['city']}")
print(f"Startup Count: {top_investor_hub['startup_count']}")
print(f"Total Funding: {top_investor_hub['total_funding']} Cr")

Investor Hub Analysis (Cities with at least 2 startups, sorted by total funding):

        city  startup_count  total_funding
3     Mumbai              2            260
0  Bengaluru              2            200

Top Investor Hub:
City: Mumbai
Startup Count: 2
Total Funding: 260 Cr

In [ ]:
import pandas as pd
import numpy as np

# Re-initializing df with data relevant to Q38: Emerging player finder
data_q38 = {
    'startup_name': ['Alpha Fintech', 'Beta Edtech', 'Gamma Health', 'Delta AI', 'Epsilon Fintech', 'Zeta Edtech'],
    'industry': ['Fintech', 'Edtech', 'HealthTech', 'AI', 'Fintech', 'Edtech'],
    'city': ['Bengaluru', 'Mumbai', 'Delhi', 'Bengaluru', 'Mumbai', 'Chennai'],
    'founded_year': [2019, 2020, 2018, 2021, 2019, 2020],
    'amount': [120, 150, 90, 80, 110, 105] # Amounts in Crores
}
df = pd.DataFrame(data_q38)

print("DataFrame re-initialized for Q38:")
display(df)

DataFrame re-initialized for Q38:

      startup_name    industry       city  founded_year  amount
0    Alpha Fintech     Fintech  Bengaluru          2019     120
1      Beta Edtech      Edtech     Mumbai          2020     150
2     Gamma Health  HealthTech      Delhi          2018      90
3         Delta AI          AI  Bengaluru          2021      80
4  Epsilon Fintech     Fintech     Mumbai          2019     110
5      Zeta Edtech      Edtech    Chennai          2020     105

In [ ]:
# Q38: Emerging player finder
# Criteria: founded in 2019 or later, funding >= 100 Cr, in Fintech/Edtech/HealthTech

emerging_players = df[
    (df['founded_year'] >= 2019) &
    (df['amount'] >= 100) &
    (df['industry'].isin(['Fintech', 'Edtech', 'HealthTech']))
]

# Sort by amount descending
emerging_players = emerging_players.sort_values(by='amount', ascending=False)

# Print requested columns
print("\nEmerging Players:")
display(emerging_players[['startup_name', 'industry', 'city', 'founded_year', 'amount']])

Emerging Players:

      startup_name industry       city  founded_year  amount
1      Beta Edtech   Edtech     Mumbai          2020     150
0    Alpha Fintech  Fintech  Bengaluru          2019     120
4  Epsilon Fintech  Fintech     Mumbai          2019     110
5      Zeta Edtech   Edtech    Chennai          2020     105

### Why might a VC analyst care about this list?

A VC analyst would care about this list for several reasons:

1.  **Early Investment Opportunity:** These are relatively new companies (founded 2019 or later) that have already secured significant funding (>= 100 Cr) in high-growth sectors (Fintech, Edtech, HealthTech). This indicates strong market potential and traction.
2.  **Growth Potential:** Identifying companies that are performing well early on can lead to follow-on investment opportunities and potentially higher returns as they scale.
3.  **Strategic Fit:** The specific industries (Fintech, Edtech, HealthTech) might align with the VC firm's investment thesis or portfolio strategy.
4.  **Competitive Landscape:** Understanding which companies are emerging and gaining traction helps in assessing the competitive landscape and identifying potential disruptors.
5.  **Benchmarking:** These companies can serve as benchmarks for evaluating other startups in similar stages and sectors.

In [ ]:
df.to_csv(
    "cleaned_indian_startups.csv",
    index=False
)

print("Dataset Saved Successfully")

Dataset Saved Successfully

Q40. Market saturation. For each combination of (city, industry), count the number of startups. Print the
top 10 most-saturated combinations. This tells a new founder where competition is most intense – and
by elimination, where the gaps might be.

In [ ]:
print(df.info())

print()

print(df.describe(include="all"))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   startup_name  6 non-null      object
 1   industry      6 non-null      object
 2   city          6 non-null      object
 3   founded_year  6 non-null      int64
 4   amount        6 non-null      int64
dtypes: int64(2), object(3)
memory usage: 372.0+ bytes
None

         startup_name industry       city  founded_year      amount
count               6        6          6      6.000000    6.000000
unique              6        4          4           NaN         NaN
top     Alpha Fintech  Fintech  Bengaluru           NaN         NaN
freq                1        2          2           NaN         NaN
mean              NaN      NaN        NaN   2019.500000  109.166667
std               NaN      NaN        NaN      1.048809   24.579802
min               NaN      NaN        NaN   2018.000000   80.000000
25%               NaN      NaN        NaN   2019.000000   93.750000
50%               NaN      NaN        NaN   2019.500000  107.500000
75%               NaN      NaN        NaN   2020.000000  117.500000
max               NaN      NaN        NaN   2021.000000  150.000000

In [ ]:
print(df.columns)

Index(['a', 'b'], dtype='object')